I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/custom/login.rpy", line 136, in script call
    call news0 from __add_news_0_
  File "game/custom/login.rpy", line 136, in script call
    call news0 from __add_news_0_
ScriptError: could not find label 'news0'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/custom/login.rpy", line 136, in script call
    call news0 from __add_news_0_
  File "/Applications/renpy-6.99.12.4-sdk/renpy/ast.py", line 1322, in execute
    rv = renpy.game.context().call(label, return_site=self.next.name)
  File "game/custom/login.rpy", line 136, in script call
    call news0 from __add_news_0_
  File "/Applications/renpy-6.99.12.4-sdk/renpy/script.py", line 858, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'news0'.

Darwin-16.7.0-x86_64-i386-64bit
Ren'Py 6.99.12.4.2187
> turing 0.1
