I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/custom/mail.rpy", line 52, in script
    if len(args) == 1 and arg[0] == "emails":
  File "game/custom/mail.rpy", line 52, in <module>
    if len(args) == 1 and arg[0] == "emails":
NameError: name 'arg' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/custom/mail.rpy", line 52, in script
    if len(args) == 1 and arg[0] == "emails":
  File "/Applications/renpy-6.99.12.4-sdk/renpy/ast.py", line 1656, in execute
    if renpy.python.py_eval(condition):
  File "/Applications/renpy-6.99.12.4-sdk/renpy/python.py", line 1749, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/Applications/renpy-6.99.12.4-sdk/renpy/python.py", line 1743, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/custom/mail.rpy", line 52, in <module>
    if len(args) == 1 and arg[0] == "emails":
NameError: name 'arg' is not defined

Darwin-16.7.0-x86_64-i386-64bit
Ren'Py 6.99.12.4.2187
> turing 0.1
